services:
  quantum-service:
    build: .
    container_name: quantum-service
    ports:
      - "8081:10000"
    networks:
      - quantum-net
    restart: unless-stopped
    environment:
      - SERVER_PORT=10000

  quantum-keymanager:
    build: ./quantum-keymanager
    container_name: quantum-keymanager
    ports:
      - "8082:10000"
    environment:
      - SPRING_PROFILES_ACTIVE=memory
      - MASTER_KEY_SECRET=super_secret_master_key_change_me_in_prod
      - API_BASE_URL=http://quantum-service:10000
    networks:
      - quantum-net
    restart: unless-stopped

  quantum-keymanager-ui:
    build: ./quantum-keymanager-ui
    container_name: quantum-keymanager-ui
    ports:
      - "3000:80"
    depends_on:
      - quantum-keymanager
    networks:
      - quantum-net
    restart: unless-stopped

  kong:
    image: kong:3.9.0
    platform: linux/amd64
    container_name: kong-gateway
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
    volumes:
      - ./kong:/usr/local/kong/declarative/
    ports:
      - "8000:8000"   # Proxy HTTP
      - "8443:8443"   # Proxy HTTPS
      - "8001:8001"   # Admin API (Local only)
    depends_on:
      - quantum-service
      - quantum-keymanager
      - quantum-keymanager-ui
    networks:
      - quantum-net
    restart: unless-stopped

networks:
  quantum-net:
    driver: bridge
